server:
  port: 8401
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka/
  instance:
    # 把自己的IP地址注册到eureka-server中
    prefer-ip-address: true
spring:
  application:
    name: member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/filmdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
  jackson:
    date-format: yyyy-MM-DD HH:mm:ss
    time-zone: GMT+8

# 关于Feign的一些配置，
feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
  # 开启feign对hystrix的支持，默认false
  hystrix:
    enabled: true
  okhttp:
    enabled: true
    # 默认使用http-client
  httpclient:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
          strategy: SEMAPHORE
